name: white_cobalt
description: Media downloader using Cobalt API
version: 0.5.0+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  flutter_downloader: ^1.11.4
  shared_preferences: ^2.2.0
  flutter_svg: ^2.1.0
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.14.3
  filesize: ^2.0.1
  fl_chart: ^1.0.0
  media_scanner: ^2.2.0
  card_loading: ^0.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: NotoSansMono
      fonts:
        - asset: fonts/NotoSansMono.ttf
          style: normal
          weight: 400
  assets:
    - assets/heart/heart.png
    - assets/heart/Heart Meowbalt.svg

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/Heart.png"
  adaptive_icon_foreground: "assets/icon/Heart.png"
  min_sdk_android: 16
  adaptive_icon_background: "#000000"
  adaptive_icon_monochrome: "assets/icon/Heart.png"